name: Build CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - CONTRIBUTING.md
      - README
      - README.md
      - RELNOTES
      - SECURITY.md
  pull_request:
    branches: [ master ]
    paths-ignore:
      - CONTRIBUTING.md
      - README
      - README.md
      - RELNOTES
      - SECURITY.md

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: update package information
      run: sudo apt-get update
    - name: install dependencies
      run: sudo apt-get install gcc-11 libapparmor-dev libselinux1-dev expect xzdec
    - name: configure
      run: CC=gcc-11 ./configure --enable-fatal-warnings --enable-analyzer --enable-apparmor --enable-selinux --prefix=/usr
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: print version
      run: command -V firejail && firejail --version
    - name: run tests
      run: SHELL=/bin/bash make test-github
