name: Build-extra CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - .git-blame-ignore-revs
      - .gitignore
      - CONTRIBUTING.md
      - COPYING
      - README
      - README.md
      - RELNOTES
      - SECURITY.md
      - 'etc/**'
      - 'src/firecfg/firecfg.config'
      - '.github/ISSUE_TEMPLATE/*'
      - '.github/pull_request_template.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - .git-blame-ignore-revs
      - .gitignore
      - CONTRIBUTING.md
      - COPYING
      - README
      - README.md
      - RELNOTES
      - SECURITY.md
      - 'etc/**'
      - 'src/firecfg/firecfg.config'
      - '.github/ISSUE_TEMPLATE/*'
      - '.github/pull_request_template.md'

jobs:
  build-clang:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: configure
      run: CC=clang-11 ./configure --enable-fatal-warnings
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: print version
      run: command -V firejail && firejail --version
  scan-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: install clang-tools-11
      run: sudo apt-get install clang-tools-11
    - name: configure
      run: CC=clang-11 ./configure --enable-fatal-warnings
    - name: scan-build
      run: NO_EXTRA_CFLAGS="yes" scan-build-11 --status-bugs make
  cppcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: install cppcheck
      run: sudo apt-get install cppcheck
    - name: cppcheck
      run: cppcheck -q --force --error-exitcode=1 --enable=warning,performance .
