name: Build-extra CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - CONTRIBUTING.md
      - README
      - README.md
      - RELNOTES
      - SECURITY.md
      - 'etc/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - CONTRIBUTING.md
      - README
      - README.md
      - RELNOTES
      - SECURITY.md
      - 'etc/**'

jobs:
  build-clang:
    if: ${{ ! contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: CC=clang-10 ./configure --enable-fatal-warnings
    - name: make
      run: make
  scan-build:
    if: ${{ ! contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install clang-tools-10
      run: sudo apt-get install clang-tools-10
    - name: configure
      run: CC=clang-10 ./configure --enable-fatal-warnings
    - name: scan-build
      run: NO_EXTRA_CFLAGS="yes" scan-build-10 --status-bugs make
  cppcheck:
    if: ${{ ! contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install cppcheck
      run: sudo apt-get install cppcheck
    - name: cppcheck
      run: cppcheck -q --force --error-exitcode=1 --enable=warning,performance .
